# Generated by Django 5.0.3 on 2024-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('aired', models.CharField(max_length=255)),
                ('episodes', models.IntegerField()),
                ('members', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('ranked', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('img_url', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
